### PR TITLE
Test action updates

### PR DESCRIPTION
**Pull request by glenn-jocher**
Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:

1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.

2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.

3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.

4. **Ultralytics Contributor License Agreement (CLA)**: To uphold the quality and integrity of our project, we require all contributors to sign the CLA. Please confirm your agreement by commenting below:

   _I have read the CLA Document and I hereby sign the CLA_

For more detailed guidance and best practices on contributing, refer to our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing). Your adherence to these guidelines ensures a faster and more effective review process.

### CODE REVIEW

**Comment by akx** [comment]
> Do you know what we need to do to allow the action to update PRs that are coming from 3rd party forks instead of branches within Ultralytics repos? 

Unfortunately I don't.

However, I'm wondering why this action is necessary – what was wrong with pre-commit? For one, these rules can't easily be enforced locally...

**Comment by glenn-jocher** [comment]
@akx I'm trying to centralize a coding standard across all ultralytics repos, which is difficult with pre-commit, it's more a per-repo mix and match.

For example if we deploy pre-commit to 10 repos and then want to update something, we have to make 10 PRs. With this method, we just change it here and don't have to make any PRs in the deployed repos.

**Comment by akx** [comment]
I'm not sure this solves that. If you change something here, you'd still need to make 10 otherwise empty PRs in the other projects that would use the then-current `ultralytics/action` to have it fix things.

I think I've seen a project that easily syncs given configuration etc. files from a "central" repo into other projects, but I can't find it right now...

**Comment by glenn-jocher** [comment]
@akx That's a valid point. The idea is to have the action run on any push to any branch, which would then keep each repo up to date without manual intervention. The action would auto-format the code on any push, so the repos would stay in sync with the central coding standard after any push to any branch. If there's a better way to do this I'm open to suggestions! 😊

**Pull request merged**
